### ISSUE TITLE
Add treat warnings as errors

### ISSUE THREAD

**Issue by mozts2005** [tom-englert/ProjectConfigurationManager#2]
Would love to see "treat warnings as errors" to be added as a property so that it could be updated. 

I am willing to help with the work just wanted to make sure that it is work that others will want as well.

**Comment by tom-englert** [comment]
Currently it only shows properties that appear in any project, so properties that not in the project file (because the just have their default values) are missing. 
As soon as you change it in at least one project, it will appear (however currently in the "Others" group).

Maybe the "well known properties" should really appear always.
